site_name: Vanna.AI Documentation
nav:
  - Intro:
    - What is Vanna.AI?: index.md
    - Intro to Vanna: intro-to-vanna.md
  - How Vanna Works:
    - Onboarding: onboarding.md
    - Adding Vanna to your Workflow: workflow.md
  - Use in Notebooks:
    - Asking Questions: notebooks/vn-ask.md
    - Training Vanna: notebooks/vn-train.md
  - Other Ways to Use Vanna:
    - Use with Streamlit: streamlit.md
  - Databases:
    - Use with your Database: databases.md
  - Advanced:
    - Code Reference: reference.md
  - Support: support.md
repo_url: https://github.com/vanna-ai/vanna-py
theme:
  icon:
    repo: fontawesome/brands/github
  logo: https://ask.vanna.ai/static/img/vanna.svg
  favicon: https://vanna.ai/favicon.ico
  name: material
  palette:
    scheme: slate
  features:
    - navigation.sections
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://vanna.ai
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - mkdocstrings
copyright: >
  Copyright &copy; 2023 Vanna.AI