name: ci 
on:
  push:
    branches:
      - main
      - update-docs-3
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: vanna-docs-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            vanna-docs-
      - run: pip install PyYAML
      - run: pip install nbconvert
      - run: pip install ghp-import
      - run: pip install pdoc
      - run: pip install .
      - run: pdoc vanna --logo https://img.vanna.ai/vanna-ref.svg --logo-link https://docs.vanna.ai --no-show-source --mermaid --docformat google -n -o docs
      - run: python docs/sidebar.py docs/sidebar.yaml notebooks docs
      - run: ghp-import -n -p -f docs
